remove address due to error in tomcat logs:
May 01, 2024 10:14:45 PM org.apache.tomcat.util.net.AbstractEndpoint logCertificate
INFO: Connector [https-openssl-nio-8443], TLS virtual host [zfin.org], certificate type [UNDEFINED] configured from keystore [/opt/apache/apache-tomcat/conf/keystore] using alias [tomcat] with trust store [null]
May 01, 2024 10:14:45 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-nio-0:0:0:0:0:0:0:1-8009"]
May 01, 2024 10:14:45 PM org.apache.catalina.util.LifecycleBase handleSubClassException
SEVERE: Failed to initialize component [Connector["ajp-nio-0:0:0:0:0:0:0:1-8009"]]
org.apache.catalina.LifecycleException: Protocol handler initialization failed
→   at org.apache.catalina.connector.Connector.initInternal(Connector.java:1016)
→   at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:127)
→   at org.apache.catalina.core.StandardService.initInternal(StandardService.java:578)
→   at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:127)
→   at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:1039)
→   at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:127)
→   at org.apache.catalina.startup.Catalina.load(Catalina.java:708)
→   at org.apache.catalina.startup.Catalina.load(Catalina.java:731)
→   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
→   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
→   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
→   at java.base/java.lang.reflect.Method.invoke(Method.java:568)
→   at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:302)
→   at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:472)
Caused by: java.nio.channels.UnsupportedAddressTypeException
→   at java.base/sun.nio.ch.Net.checkAddress(Net.java:161)
→   at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:330)
→   at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
→   at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:239)
→   at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:194)
→   at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1307)
→   at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1320)
→   at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:624)
→   at org.apache.catalina.connector.Connector.initInternal(Connector.java:1014)
→   ... 13 more