Properties ectomy2 (#25)
* ZFIN-9933: Gradle upgrade but downgrade to match deps (#21)

* progress toward war packaging
upgrade lucene api usage
delete unneeded jars
Remove embedded jackson lib in robot.jar to fix error:

    java.lang.NoSuchMethodError: 'com.fasterxml.jackson.databind.cfg.MutableCoercionConfig com.fasterxml.jackson.dataformat.xml.XmlMapper.coercionConfigDefaults()'
        at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:184)
        at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:153)
        at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:135)
        at org.hibernate.type.format.jackson.JacksonXmlFormatMapper.createXmlMapper(JacksonXmlFormatMapper.java:46)
        at org.hibernate.type.format.jackson.JacksonXmlFormatMapper.<init>(JacksonXmlFormatMapper.java:38)
        at org.hibernate.type.format.jackson.JacksonIntegration.<clinit>(JacksonIntegration.java:17)

* remove angular directive files

ZFIN-9994: delete unneeded jars

ZFIN-9994: Remove unneeded jar files. restygwt is necessary because there is no upstream version with jakarta
ZFIN-9994: re-add javassist because it is needed by gwt (see FeatureAddView import javassist.compiler.ast.StringL)
ZFIN-9994: Remove log4j references (replaced with log4j2)
ZFIN-9994: Remove directories from settings.gradle if they do not contain build.gradle
ZFIN-9994: Do not need explicit "AntBuilder()" constructor invocation in new version of ant <groovy> taskdef
ZFIN-9994-warversion: Create a warfile for deployment
ZFIN-9994-warversion: Add an application target so we can run tasks without gradle
ZFIN-9994-warversion: Remove analytics uberjar from local repo

* ZFIN-9994: Remove autodeploy

* ZFIN-9994: Remove outdated deploy targets

* ZFIN-9994: Add gradle tasks to reload class files quickly after code changes
ZFIN-9994: Fix deprecated setting for destination dir
ZFIN-9994: Add dirtydeploy task again.
ZFIN-9994: Fix dependency needed for tests

* ZFIN-9994: Remove static files that are not needed in the war file (they are served by apache)

* ZFIN-9994: Use database to store release version information

* ZFIN-9994: Remove pre-home / post-home logic

* ZFIN-9994: Be consistent in naming releaseNumber instead of releaseVersion

* Upgrade groovy in github action

* use maven for text-table-formatter

* remove cvu.jar as it is not used anymore (only reference is unused)

* remove jars

* update to match newer names

* do not fail build if deployGitInfo fails

* Add more captcha blocking logic (on POSTs)

* ZFIN-9994: Fix `gradle runEnsemblTranscriptLengthUpdater` issue

* Update paths for WAR file deployment compatibility

   - Add ZFIN_PROPERTIES_PATH env var pointing to deployed WAR location
   - Update GROOVY_CLASSPATH to use CATALINA_BASE/webapps/ROOT/WEB-INF
   - Update ~45 Groovy scripts to use ZFIN_PROPERTIES_PATH
   - Update ZFINPerlModules.pm to use ZFIN_PROPERTIES_PATH
   - Update Jenkins job configs with new properties file paths
   - Fix Groovy 4.x compatibility: use groovy.xml.XmlSlurper and
     groovy.xml.slurpersupport.GPathResult imports

* ZFIN-9994: new property

* ZFIN-9994: remove legacy biojava

* ZFIN-9994: use gradle for test

* ZFIN-9994: use $WAR_WEB_INF_DIR to reference the deployment location of WEB-INF

* ZFIN-9972: Replace ~/.gradle with /home/gradle/.gradle

* ZFIN-9916: Introduce new classpath values for the deployed location of jars

* ZFIN-9916: Introduce new classpath values for the deployed location of jars

* ZFIN-9916: Remove log4j version 1 formatting

* ZFIN-9916: Fix errors in output:

```
Buildfile: /opt/zfin/source_roots/zfin.org/build.xml
  [taskdef] ERROR StatusConsoleListener root contains an invalid element or attribute "priority"
  [taskdef] ERROR StatusConsoleListener Unknown object "root" of type org.apache.logging.log4j.core.config.LoggerConfig is ignored: try nesting it inside one of: ["Appenders", "Loggers", "Properties", "Scripts", "CustomLevels"].
```

* ZFIN-9916: fix classpath issues for ant

* ZFIN-9916: fix JDBC connection issues for solr

* ZFIN-9916: Fix ant task to output graph of ant targets using "grand" library

* ZFIN-9916: Use gradle wrapper in ant tasks that use gradle

* ZFIN-9916: Remove "grand" library. Include message for instructions if we want to re-include it.

* ZFIN-9916: Add gradlew files

* ZFIN-9916: Use "$HOME" instead of /home/gradle for files that have access to env vars.

* Refactor environment property handling and update related scripts.

New build method will only commit single file for each instance ($instance.properties) instead of 4 files (.properties, .bash, .env, .tt).

Instead of an $instance.bash file, we use load-properties.bash to read the zfin.properties file into the environment.

* Improve properties file handling by attempting to generate it if not found

* Update PostgreSQL configuration to allow trust connections from specific IP range

* Update properties files to include defaults from the 'defaults' directory

* WIP: Update properties files to include defaults from the 'defaults' directory

* Remove unnecessary properties: WEBHOST_HOSTNAME, HOSTNAME, MACHINE_NAME

* Prototype of one yaml to rule them all

* Rearrange properties file

* Rearrange properties file

* use prefix for env vars

* Add comments for documentation

* Create a groovy parser that can read yaml and output properties

* Fill out the overrides for some VMs

* Update usage instructions and enforce INSTANCE environment variable requirement

* Add staging environment defaults and enhance overwrite logging in PropertiesProcessor

* Add SMTP host and SOLR backup settings to "production" section in all-properties.yml

* Add a presentation explaining the point of this branch

* Update presentation explaining the point of this branch

* Minor tweak